language: go

go:
  - 1.11.x
  - 1.12.x
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert

os:
  - linux

script:
  - go test -race -v +local
  - $HOME/gopath/bin/goveralls -service=travis-ci
